---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bamboo-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bamboo-operator
subjects:
  - kind: ServiceAccount
    name: bamboo-operator
    namespace: atl
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo-operator
  labels:
    k8s-app: bamboo-operator
spec:
  selector:
    matchLabels:
      k8s-app: bamboo-operator
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: bamboo-operator
    spec:
      serviceAccountName: bamboo-operator
      containers:
        - name: bamboo-operator
          image: yivantsov/bamboo-operator:0.1.0
          imagePullPolicy: Always
