# permissions for end users to view bambooes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bamboo-viewer-role
rules:
- apiGroups:
  - install.atlassian.com
  resources:
  - bambooes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.atlassian.com
  resources:
  - bambooes/status
  verbs:
  - get
