
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - install.atlassian.com
  resources:
  - bambooes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.atlassian.com
  resources:
  - bambooes/status
  verbs:
  - get
  - patch
  - update
